### PR TITLE
Reworked script for macOS

### PR DESCRIPTION
**Pull request by staatzstreich**
Hey @Jiab77 ... as mentioned before. This is like I would write it. Not necessay do it like this :)

### CODE REVIEW

**Comment by Jiab77** [comment]
@staatzstreich, Thanks a lot for your PR, I like the way you did things!

**Comment by Jiab77** [comment]
@staatzstreich, Thanks again for your work and sorry for the delay it took to be merged.

**Comment by staatzstreich** [comment]
Thanks for merging and mention!

**Comment by Jiab77** [comment]
@staatzstreich, it's normal, you deserved it, your code is even better than mine 😅

**Pull request merged**
